version: 0.2
env:
  secrets-manager:
    LOGIN: sonarqube-secret:sonartoken
    HOST: sonarqube-secret:HOST
    Project: sonarqube-secret:project
    Sonar_credentials: sonarqube-secret:sonarcredentials
phases:
  install:
    runtime-versions:
      java: corretto11.x
      java: corretto8.x
  pre_build:
    commands:
      - yum update -y
      - yum install -y ruby wget
      - yum install unzip -y
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
      - unzip ./sonar-scanner-cli-4.4.0.2170-linux.zip
      - export PATH=$PATH:/sonar-scanner-4.4.0.2170-linux/bin/
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - export JAVA_HOME="/usr/lib/jvm/java-11-amazon-corretto.x86_64"
      - PATH=$JAVA_HOME/bin:$PATH
      - export PATH=$PATH:$JAVA_HOME/bin
      - echo $JAVA_HOME
      - echo $HOST
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project
      - ls -ltr
reports:
  arn:aws:codebuild:ap-south-1:033698541909:report-group/analysis-reports:
    files:
      - target/jacoco-ut/jacoco.xml
    file-format: xml       
artifacts:
  type: zip
  files: '**/*'
      
